### PR TITLE
Cee/fix navbar/ticket 1

### PR DESCRIPTION
**Pull request by CeeFish**
## Description

Navbar styling and links match. Navbar only shows up once the user has signed up/logged in.

## Changelog

Internal changes
Removed old navbar that was in the middle of the page and on landing page.

External changes
Added links for the profile page, groups page, and meetups page.

## PR Checklist

- [x] Write clear, easy to read description of PR
- [x] Remove all text from PR description that is in (parenthesis)
- [x] Add and label screenshots (if dealing with UI. if not, delete this line)
- [x] Remove debugging statements like `console.log`, `byebug`, `puts`, `prints`, `p`, `pp`

## How does this PR make you feel?

Select a gif or emoji and add here. You can find gifs here: https://giphy.com/categories/emotions

### CODE REVIEW

**Review by myang1010 — COMMENTED** [review]
Thanks Candace. Changes looks good. I also have a question for the Begin and End block.
Since I couldn't run the code and see the change, I'd leave it as reviewed but not merged. 
Thanks.

**Review by sheilahd — CHANGES_REQUESTED** [review]
Let us know when you finish taking a look at the comments we left.

**Comment by sheilahd** [comment]
@CeeFish Changes look good. Just resolve the conflicts so we can merge in..

**Comment by CeeFish** [comment]
I have resolved the conflict’s multiple times but because I can’t commit the merge it it’s not saving them.

**Review by myang1010 — APPROVED** [review]

**Pull request merged**
